# Site settings
title: Prework
email: hola@hackerschool.mx
description: > # this means to ignore newlines until "baseurl:"
  HSMTY es una escuela que busca profesionalizar a desarrolladores
  de software, donde tendrás 13 semanas de entrenamiento hacker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackerschool.mx/" # the base hostname & protocol for your site
twitter_username: hackerschoolmty
github_username:  hackerschoolmty

# Build settings
markdown: kramdown
